import * as fs from 'fs';
import * as path from 'path';
import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Self-hosted @font-face rules (generated by scripts/fetch-fonts.mjs). We
// inline them into <head> via injectHtmlTags (see the plugin at the bottom)
// rather than importing through theme.customCss on purpose: css-loader would
// content-hash the url('/fonts/…') refs into /assets/fonts/…-<hash>.woff2,
// which then wouldn't match the /fonts/… <link rel=preload> below (wasted
// double-download). Inlining keeps the URLs literal AND declares the fonts
// during HTML parse, so the preloaded woff2 is actually the one used.
const fontFaceCss = fs
  .readFileSync(path.resolve(__dirname, 'src/css/fonts.css'), 'utf8')
  // Strip CSS comments so we don't ship the header block inline on every page.
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .trim();

const config: Config = {
  title: 'Pagine Giappe',
  tagline: 'La Jekucina a casa tua!',
  // Use a typographic middle dot in <title> tags ("Page · Site") instead of
  // the default pipe — cleaner on the SERP and the browser tab.
  titleDelimiter: '·',
  favicon: 'img/favicon.ico',
  trailingSlash: true,
  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'throw'
    },
  },

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  url: 'https://paginegiappe.it',
  baseUrl: '/',

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: 'amicojeko', // Usually your GitHub org/user name.
  projectName: 'japanesecookbook', // Usually your repo name.

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  // Defer Docusaurus's on-viewport route prefetching until the page is idle.
  // Without this the home hub fires ~180 <link rel="prefetch"> during load and
  // starves the LCP resources on slow mobile (regressed home LCP 7.0s → 9.1s).
  clientModules: [
    require.resolve('./src/clientModules/deferPrefetch.ts'),
    // Background pre-warm of recipe hero photos into the SW image cache, so
    // recipes are available offline with a photo. See the file for the
    // politeness guards (Save-Data, slow connection, 24h throttle).
    require.resolve('./src/clientModules/pwaWarmImages.ts'),
  ],

  i18n: {
    defaultLocale: 'it',
    locales: ['it'],
  },

  // Fonts are self-hosted (static/fonts/*.woff2) and declared via @font-face in
  // src/css/fonts.css, which Docusaurus bundles into the theme stylesheet (see
  // theme.customCss below). This removes the render-blocking request to
  // fonts.googleapis.com that was costing ~1.2s on mobile first paint.
  // Regenerate the woff2 + fonts.css with `node scripts/fetch-fonts.mjs`.
  //
  // Preload the two Newsreader latin faces used above the fold (body @500,
  // headings @700) so they start downloading in parallel with the CSS instead
  // of after it parses. crossorigin is required even same-origin: font fetches
  // are always CORS-anonymous, so the preload must match to be reused.
  headTags: [
    {
      tagName: 'link',
      attributes: {
        rel: 'preload',
        href: '/fonts/newsreader-500-latin.woff2',
        as: 'font',
        type: 'font/woff2',
        crossorigin: 'anonymous',
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'preload',
        href: '/fonts/newsreader-700-latin.woff2',
        as: 'font',
        type: 'font/woff2',
        crossorigin: 'anonymous',
      },
    },
  ],

  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          showLastUpdateTime: true,
          showLastUpdateAuthor: true,
        },
        blog: {
          path: './blog',
          routeBasePath: '/blog',
          blogTitle: 'Blog · Pagine Giappe',
          blogDescription:
            'Appunti, novità e riflessioni dal taccuino di cucina giapponese di Pagine Giappe: ricette, ingredienti, negozi orientali in Italia e viaggi in Giappone.',
          blogSidebarTitle: 'Ultimi post',
          blogSidebarCount: 10,
          postsPerPage: 10,
          authorsMapPath: 'authors.yml',
          showReadingTime: true,
          // Honor `hide_reading_time: true` in a post's frontmatter to
          // suppress the strip on a single post. Otherwise use 350 wpm
          // (Docusaurus default is 200; we bump it to better match how
          // people actually skim editorial-blog content). Keep this in
          // sync with READING_WPM in scripts/generate-blog-index.js so the
          // homepage strip and the post header show the same number.
          readingTime: ({content, frontMatter, locale, defaultReadingTime}) =>
            frontMatter.hide_reading_time
              ? undefined
              : defaultReadingTime({
                  content,
                  locale,
                  options: {wordsPerMinute: 350},
                }),
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
            title: 'Pagine Giappe — Blog',
            description:
              'Appunti dal taccuino di cucina giapponese in italiano di Stefano "Jeko" Guglielmetti.',
            copyright: `© ${new Date().getFullYear()} Stefano Guglielmetti — paginegiappe.it`,
            language: 'it',
          },
          onInlineTags: 'throw',
          onInlineAuthors: 'throw',
          onUntruncatedBlogPosts: 'throw',
        },
        theme: {
          // @font-face lives in src/css/fonts.css but is injected inline in
          // <head> (see inline-fontface plugin below), not bundled here, so the
          // /fonts/ URLs stay literal and the preload is actually reused.
          customCss: './src/css/custom.css',
        },
        // gtag plugin only in production builds. In dev its route-update
        // callback can fire before window.gtag is bound (HMR / build-while-dev
        // races), throwing "window.gtag is not a function". Disabling in dev
        // also keeps local pageviews out of GA.
        gtag:
          process.env.NODE_ENV === 'production'
            ? {
                trackingID: 'G-YZDG2VN7ZG',
                anonymizeIP: true,
              }
            : undefined,
        // Sitemap: explicit config (preset-classic enables the plugin by
        // default with priority 0.5 and no ignorePatterns). We pin priority
        // to 0.7 to signal these pages as above-average importance, and skip
        // the auto-generated utility/thin pages to free crawl budget — they
        // showed up empty / "Crawled - currently not indexed" in GSC.
        // These same routes also carry a `noindex` meta tag (swizzle wrappers
        // in src/theme/) so Google won't index them even if it reaches them
        // via internal links rather than the sitemap.
        // `lastmod: 'date'` emits a <lastmod>YYYY-MM-DD</lastmod> per URL
        // (from frontmatter date / git history) so Google can prioritize
        // crawling of new and recently updated pages — without it new blog
        // posts get stuck in "Discovered – currently not indexed".
        sitemap: {
          lastmod: 'date',
          changefreq: 'weekly',
          priority: 0.7,
          ignorePatterns: [
            '/tags/**', // docs tag pages
            '/blog/tags/**',
            '/blog/authors/**',
            '/blog/archive/**',
            '/blog/page/**', // blog index pagination (page 2+); /blog/ stays
            '/search/',
          ],
          filename: 'sitemap.xml',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    algolia: {
      appId: '9DWNYPKJD0',
      apiKey: 'b31d01c5282cee1939baf74e884ce829',
      indexName: 'ricettegiapponesi',
      contextualSearch: true,
      insights: true,
      placeholder: 'Cerca ricette e ingredienti',
      searchParameters: {
        distinct: 1,
      },
      // Optional: path for search page that enabled by default (`false` to disable it)
      // searchPagePath: 'search',
    },
    image: 'img/social_media_card.png',
    metadata: [
      // Card format only. Twitter/X falls back to og:title / og:description
      // when twitter:title / twitter:description aren't set — and Docusaurus
      // auto-generates og:* per page from frontmatter (title / description
      // / image), so setting twitter:title / twitter:description here would
      // hardcode site-wide strings on every page (already happened: blog
      // posts showed "Le ricette giapponesi di Jeko" instead of the post
      // title on X cards). Keep this minimal; let og:* be the single source
      // of truth. twitter:image is auto-emitted per page by Docusaurus.
      {name: 'twitter:card', content: 'summary_large_image'},
      {
        name: 'description',
        content: 'Cucina casalinga giapponese autentica in italiano: ricette di casa e da izakaya spiegate passo passo, con foto e video. Niente fusion, niente all you can eat.'
      },
      // Performance optimizations
      {name: 'referrer', content: 'strict-origin-when-cross-origin'},
      {httpEquiv: 'x-ua-compatible', content: 'IE=edge'},
    ],
    colorMode: {
      defaultMode: 'light',
      disableSwitch: true,
      respectPrefersColorScheme: false,
    },
    navbar: {
      title: 'Pagine Giappe',
      logo: {
        alt: 'Jeko',
        src: 'img/logo_katakana.png',
      },
      items: [
        {
          to: '/ricette',
          label: 'Ricette',
          position: 'left'
        },
        {
          to: '/negozi_orientali',
          label: 'Negozi',
          position: 'left'
        },
        {
          to: '/viaggi',
          label: 'Viaggi',
          position: 'left'
        },
        {
          to: '/libri',
          label: 'Libri',
          position: 'left'
        },
        {
          to: '/blog',
          label: 'Blog',
          position: 'left'
        },
        {
          href: 'https://github.com/amicojeko/japanesecookbook',
          label: 'GitHub',
          position: 'right',
          // Hidden when running as an installed app (see the
          // display-mode: standalone rules in src/css/custom.css).
          className: 'navbar-github-link',
        },
      ],
    },
    // No `footer:` block here on purpose. The footer is fully swizzled in
    // src/theme/Footer/index.tsx (custom 4-column layout with PayPal CTA, kanji
    // brand mark, etc.) and never reads from themeConfig.footer. Keeping a
    // config-side footer here would silently drift from what's actually
    // rendered — edit src/theme/Footer/index.tsx to change footer content.
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,

  plugins: [
    [
      '@docusaurus/plugin-ideal-image',
      { quality: 80, max: 1600, min: 320, steps: 4, disableInDev: false }
    ],
    // Progressive Web App: installable, app-shell offline. The plugin is
    // disabled in dev (SW only builds in `docusaurus build`), so it doesn't
    // interfere with `npm start` or the gtag dev-race noted above.
    //
    // OFFLINE STRATEGY = "leggera": precache only the app shell
    // (JS/CSS/HTML/fonts + the small image-manifest JSON). Because Docusaurus
    // bakes page content into JS chunks, precaching JS already gives installed
    // users offline access to all TEXT content. We deliberately exclude the
    // ~68MB of recipe photos (jpg/jpeg/webp) and the 400KB AI knowledge export
    // from precache — photos are runtime-cached (CacheFirst) as visited, see
    // src/sw-custom.js. This avoids a multi-megabyte download at install time.
    //
    // offlineModeActivationStrategies (plugin default): caching only kicks in
    // for installed / standalone users (or ?offlineMode=true), so regular
    // browser-tab visitors get no unexpected storage usage.
    [
      '@docusaurus/plugin-pwa',
      {
        debug: false,
        // 'always' = offline for EVERY visitor, not just installed/standalone.
        // The goal is recipes available offline by default: since Docusaurus
        // bakes page content into JS chunks (all precached), the text of every
        // recipe is offline-ready right after the first visit — no install and
        // no need to open each recipe first. Photos are still runtime-cached
        // (CacheFirst) as visited, see src/sw-custom.js, since precaching all
        // ~68MB of them would be a huge background download.
        // Freshness ("sempre aggiornate") is preserved by: sw.js served
        // no-cache (netlify.toml) + Workbox precache revisioning + the custom
        // "Nuova versione disponibile" reload popup (src/theme/PwaReloadPopup).
        offlineModeActivationStrategies: ['always'],
        swCustom: require.resolve('./src/sw-custom.js'),
        injectManifestConfig: {
          // NOTE: the plugin hardcodes `globPatterns` and overrides anything we
          // pass here (see @docusaurus/plugin-pwa lib/index.js) — its default
          // precaches js/json/css/html/fonts AND images (png,jpg,jpeg,gif,svg,ico).
          // The one lever we DO control is `globIgnores`, so we use it to carve
          // the ~68MB of recipe photos and the 400KB AI export back out of the
          // precache. The small image-*.json manifests stay precached (they're
          // read at runtime by OptimizedImage/DocCard). Photos are runtime-cached
          // instead — see src/sw-custom.js.
          globIgnores: [
            '**/*.{jpg,jpeg,webp}',
            '**/paginegiappe-knowledge.json',
          ],
          maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
        },
        pwaHead: [
          { tagName: 'link', rel: 'manifest', href: '/manifest.json' },
          { tagName: 'meta', name: 'theme-color', content: '#ffdc06' },
          { tagName: 'meta', name: 'mobile-web-app-capable', content: 'yes' },
          { tagName: 'meta', name: 'apple-mobile-web-app-capable', content: 'yes' },
          {
            tagName: 'meta',
            name: 'apple-mobile-web-app-status-bar-style',
            content: 'default',
          },
          {
            tagName: 'meta',
            name: 'apple-mobile-web-app-title',
            content: 'Pagine Giappe',
          },
          {
            tagName: 'link',
            rel: 'apple-touch-icon',
            href: '/img/pwa/apple-touch-icon.png',
          },
        ],
      },
    ],
    // Inline the self-hosted @font-face rules into <head> so the browser
    // discovers the fonts during HTML parse (paired with the /fonts/ preloads
    // in headTags). Kept out of the webpack CSS pipeline to preserve literal
    // /fonts/ URLs — see the fontFaceCss note near the top of this file.
    function inlineFontFacePlugin() {
      return {
        name: 'inline-fontface',
        injectHtmlTags() {
          return {
            headTags: [`<style>${fontFaceCss}</style>`],
          };
        },
      };
    },
  ]
};

export default config;
