// AUTO-GENERATED by scripts/generate-blog-index.js — do not edit by hand.

export type BlogIndexAuthor = {
  key: string;
  name: string;
  title?: string | null;
  imageURL?: string | null;
};

export type BlogIndexEntry = {
  slug: string;
  permalink: string;
  title: string;
  description: string | null;
  image: string | null;
  date: string;
  /** Reading time in minutes (float). null when hide_reading_time is set. */
  readingTime: number | null;
  authors: BlogIndexAuthor[];
};

export const BLOG_INDEX: BlogIndexEntry[] = [
  {
    "slug": "distributori-automatici-giappone",
    "permalink": "/blog/distributori-automatici-giappone/",
    "title": "Jidōhanbaiki: perché in Giappone i distributori automatici sono ovunque",
    "description": "Ramen istantanei, uova, biancheria, carne di Kobe: in Giappone i distributori automatici sono ovunque. Storia, invenzioni e leggende dei jihanki, dal primo del 1904 alle lattine calde fino al ruolo di infrastruttura d'emergenza.",
    "image": "/img/blog/jidohanbaiki/jidohanbaiki3.jpg",
    "date": "2026-05-15",
    "readingTime": 2.18,
    "authors": [
      {
        "key": "fujitivo",
        "name": "Erick \"il Fujitivo\"",
        "imageURL": "/img/authors/logo_ilfujitivo.png",
        "title": "Viaggiatore in Giappone dal 2008 · autore di \"Andiamo in Giappone\""
      }
    ]
  },
  {
    "slug": "il-chicco-di-sangue",
    "permalink": "/blog/il-chicco-di-sangue/",
    "title": "Il chicco di sangue: come il riso ha creato (e distrutto) il Giappone",
    "description": "Per millenni in Giappone il riso non è stato cibo: è stato moneta, esercito, energia. Dal sistema Koku alle 2500 varietà, viaggio nel chicco che ha forgiato l'identità di un popolo.",
    "image": "/img/blog/riso/agricoltori_nella_risaia.jpg",
    "date": "2026-05-15",
    "readingTime": 3.1,
    "authors": [
      {
        "key": "curiosity_power",
        "name": "Mattia di Sangro \"Curiosity Power\"",
        "imageURL": "/img/authors/curiosity_power.jpg",
        "title": "Divulgatore di storia e cultura, amante del Giappone"
      }
    ]
  },
  {
    "slug": "chi-e-aki",
    "permalink": "/blog/chi-e-aki/",
    "title": "Mi presento: sono Aki, cuoco giapponese a Chioggia",
    "description": "Sono Akifumi Nakagoe, cuoco giapponese di Fukuoka trasferitosi a Chioggia nel 2024. Da oggi mi unisco a Pagine Giappe per raccontare la cucina del mio paese con quello che si trova al supermercato italiano.",
    "image": "/img/blog/aki_nakagoe.jpg",
    "date": "2026-05-14",
    "readingTime": 1.1,
    "authors": [
      {
        "key": "aki",
        "name": "Aki Nakagoe",
        "imageURL": "/img/authors/aki_nakagoe.jpg",
        "title": "Cuoco giapponese e divulgatore della cucina washoku casalinga"
      }
    ]
  },
  {
    "slug": "cosa-definisce-il-ramen",
    "permalink": "/blog/cosa-definisce-il-ramen/",
    "title": "Cosa definisce il ramen? Storia e varietà più comuni",
    "description": "Cos'è davvero il ramen? Dal kansui che lo distingue da tutti gli altri noodle in brodo alle varietà più popolari: shoyu, shio, tonkotsu, iekei, niboshi, Sapporo miso.",
    "image": "/img/blog/Shoyu_ramen_Hayashida_Ikebukuro.jpg",
    "date": "2026-05-12",
    "readingTime": 3.75,
    "authors": [
      {
        "key": "aki",
        "name": "Aki Nakagoe",
        "imageURL": "/img/authors/aki_nakagoe.jpg",
        "title": "Cuoco giapponese e divulgatore della cucina washoku casalinga"
      }
    ]
  },
  {
    "slug": "chi-e-il-fujitivo",
    "permalink": "/blog/chi-e-il-fujitivo/",
    "title": "Mi presento: sono Erick, «il Fujitivo»",
    "description": "Sono Erick Simionato, alias il Fujitivo: viaggiatore in Giappone dal 2008, autore di «Andiamo in Giappone». Da oggi mi unisco a Pagine Giappe per parlarvi di viaggi.",
    "image": "/img/authors/logo_ilfujitivo.png",
    "date": "2026-05-09",
    "readingTime": 0.65,
    "authors": [
      {
        "key": "fujitivo",
        "name": "Erick \"il Fujitivo\"",
        "imageURL": "/img/authors/logo_ilfujitivo.png",
        "title": "Viaggiatore in Giappone dal 2008 · autore di \"Andiamo in Giappone\""
      }
    ]
  },
  {
    "slug": "pesce-guarda-a-sinistra",
    "permalink": "/blog/pesce-guarda-a-sinistra/",
    "title": "Il mistero del pesce che guarda a sinistra in Giappone: un viaggio tra miti, etichetta e sogliole ribelli!",
    "description": "Nei piatti, sui libri, sulle stampe, sulle emoji: in Giappone il pesce guarda sempre a sinistra. Perché? Cinque teorie e un'eccezione (la sogliola).",
    "image": "/img/blog/il_pesce_guarda_sempre_a_sinistra.jpg",
    "date": "2026-05-09",
    "readingTime": 3.74,
    "authors": [
      {
        "key": "jeko",
        "name": "Stefano \"Jeko\" Guglielmetti",
        "imageURL": "/img/JEKO-CUCINA-02.png",
        "title": "Curatore di Pagine Giappe · nerd impenitente e cuoco amatoriale ostinato"
      }
    ]
  }
];
