// AUTO-GENERATED by scripts/generate-blog-index.js — do not edit by hand.

export type BlogIndexAuthor = {
  key: string;
  name: string;
  title?: string | null;
  imageURL?: string | null;
};

export type BlogIndexEntry = {
  slug: string;
  permalink: string;
  title: string;
  description: string | null;
  image: string | null;
  date: string;
  authors: BlogIndexAuthor[];
};

export const BLOG_INDEX: BlogIndexEntry[] = [
  {
    "slug": "benvenuti-nel-blog",
    "permalink": "/blog/benvenuti-nel-blog/",
    "title": "Chi sono, e perché esiste questo blog",
    "description": "Apriamo una sezione blog su paginegiappe.it per raccontare le novità del sito, gli ingredienti che proviamo, i negozi che scopriamo e i viaggi in Giappone.",
    "image": "/img/social_media_card.png",
    "date": "2026-05-08",
    "authors": [
      {
        "key": "jeko",
        "name": "Stefano \"Jeko\" Guglielmetti",
        "imageURL": "/img/JEKO-CUCINA-02.png",
        "title": "Curatore di Pagine Giappe · nerd impenitente e cuoco amatoriale ostinato"
      }
    ]
  }
];
